### ISSUE TITLE
[BUG] Existing gauge cards disappeared after installing energy-gauge-bundle-card

### ISSUE THREAD

**Issue by banan77** [flixlix/energy-gauge-bundle-card#7]
**Describe the bug**
All gauge cards disappeared after installation of this via HACS
**To Reproduce**
1. Install energy-gauge-bundle-card using HACS
2. Reload frontend
3. All previously created 'standard' gauge cards are not visible. In cards editor shows message "No visual editor available for type 'gauge' " New 'standard' gauge cards can't be created due to same error. Browser cache was cleared, page reloaded, etc.
4. Uninstall/remove energy-gauge-bundle-card using HACS, reload frontend - all gauge cards are visible again

**Expected behavior**
don't destroy standard cards 

**Desktop (please complete the following information):**
 - OS: 
Home Assistant 2023.7.3
Supervisor 2023.07.1
Frontend 20230705.1
 - Browser chrome, ios app

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-gauge-bundle-card/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by gavinsmith1971** [comment]
Can confirm that this is the case. When installed via HACS, standard gauges can't be created - and the editor that appears for this card seems to be some version of the original one, but without some of options that this claims to have (decimal not int for max/min etc).

Has to be removed to get normal gauges back.

**Comment by AFumi39** [comment]
I confirm that this happens to me too. The js error is
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "ha-gauge" has already been used with this registry

So you just redefined ha-gauge that's already defined. Fix it, please

**Comment by karaminder** [comment]
Triple confirming this behavior. Removing this component allows my gauges to load.

**Comment by shampeon** [comment]
Yet another confirmation. If I click Edit on the original gauge card I get:

> No visual editor available for type 'gauge'.

**Comment by Destroyer061090** [comment]
same issues also with follow version:

OS:
Home Assistant 2023.8.0
Supervisor 2023.08.0
Frontend 20230802.0

**Comment by AdriVillaB** [comment]
Same issue here

**Comment by dietmar68** [comment]
Same issue here

**Comment by sammyh2506** [comment]
Ditto.

**Comment by flixlix** [comment]
sorry for the inconvenience, fixed this issue in version 0.0.3

**Comment by AdriVillaB** [comment]
Thanks!

**Comment by AFumi39** [comment]
It works on 2023.8.1 👍
